version: '3.3'
services:
  api:
    container_name: 'api'
    build: '.'
    ports:
      - '8080:80'
    volumes:
      - '.:/go/src/app'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:4.2'
    container_name: 'mongo'
    ports:
      - '27017:27017'
