version: '3.3'
services:
  api:
    build: '.'
    container_name: 'api'
    depends_on:
      - 'mongo'
    ports:
      - '8080:80'
    networks:
      mongo_net:
        ipv4_address: 172.16.0.6
  mongo:
    image: 'mongo:4.2'
    container_name: 'mongo'
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'
    networks:
      mongo_net:
        ipv4_address: 172.16.0.5
    command: mongod --bind_ip 172.16.0.5

networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/24

volumes:
  mongodata: